### ISSUE TITLE
Caliper 1.1 compatible?

### ISSUE THREAD

**Issue by odowdj** [Apereo-Learning-Analytics-Initiative/lai-event#1]
Hi there,

Could you confirm if this repo is compatible with Caliper 1.1 spec please?
https://www.imsglobal.org/sites/default/files/caliper/v1p1/caliper-spec-v1p1/caliper-spec-v1p1.html

If not, are there any plans to update it to make it 1.1 compatible?

Thanks
James.

**Comment by ggilbert-unicon** [comment]
Hi James,

It supports 1.0 now but we'd love to add 1.1 support - just haven't had the opportunity yet.

Best,
Gary

**Comment by odowdj** [comment]
Hi Gary,

Ok, no worries, thanks for coming back to me 👍 

James.
